package model;

import java.time.LocalDate;

/**
 * Simple model class representing one row of the "transactions" table.
 * Holds no logic other than plain data access (getters/setters).
 */
public class Transaction {

    private int id;
    private String type;            // "Income" or "Expense"
    private double amount;
    private LocalDate transactionDate;

    public Transaction() {
    }

    /** Full constructor - used when reading a row back from the database. */
    public Transaction(int id, String type, double amount, LocalDate transactionDate) {
        this.id = id;
        this.type = type;
        this.amount = amount;
        this.transactionDate = transactionDate;
    }

    /** Constructor used before an id has been generated by the database. */
    public Transaction(String type, double amount, LocalDate transactionDate) {
        this.type = type;
        this.amount = amount;
        this.transactionDate = transactionDate;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public LocalDate getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(LocalDate transactionDate) {
        this.transactionDate = transactionDate;
    }
}
